name: tesla_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  flutter_bloc: ^8.1.3
  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/fonts/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-Semibold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200

